optdepends=(
    # Desktop
    "firefox-developer-edition"
    "flatpak"
    "gnome-calculator"
    "smile"
    "breeze"
    "breeze-icons"
    "mpv"
    "pacseek"
    "ttf-ms-win11-auto"
    "1password"
    "1password-cli"
    "fish"
    "neovide"
    "obsidian"
    "onedrivegui"
    "openconnect"
    "task"
    "thunderbird"
    "vit"

    # utils
    "bat"
    "btop"
    "darkman"
    "fd"
    "fzf"
    "magic-wormhole"
    "ripgrep"
    "shellcheck"

    # DevOps
    "act"
    "ansible"
    "docker"
    "docker-buildx"
    "docker-compose"
    "fluxcd"
    "github-cli"
    "kubectl"
    "sops"
    "visual-studio-code-bin"

    # System
    "btrfs-grub"
    "grub-hook"
    "informant"
    "pacdiff-pacman-hook-git"
    "pacman-log-orphans-hook"
)
